### ISSUE TITLE
Missing user names

### ISSUE THREAD

**Issue by mauromsl** [NYULibraries/intransition#1]
In many cases, the user name has not been exported in the JSON documents, despite being present on the website

e.g (editor): https://github.com/NYULibraries/intransition/blob/ac6600b7d68eea9a4169c212c502ccaa69b4f789/entities/a-history-of-the-world-according-to-getty-images.json#L30

e.g. (reviewer): https://github.com/NYULibraries/intransition/blob/ac6600b7d68eea9a4169c212c502ccaa69b4f789/entities/a-womans-place-home-in-cinema.json#L74

**Comment by dismorfo** [comment]
@mauromsl Please take a look.
