### ISSUE TITLE
Missing URLs of issue stills/images and issue blurb/description

### ISSUE THREAD

**Issue by mauromsl** [NYULibraries/intransition#2]
Add a an attribute similar to `"representative_image"` in other object schemas to `"part_of"` that points to the Issue image.
We also need the issue blurb/description to be exposed

e.g:
https://mediacommons.org/intransition/journal-videographic-film-moving-image-studies-102-2023

![image](https://github.com/NYULibraries/intransition/assets/10760678/b0d89bca-fd04-4b41-93a6-7ffd3bf34c64)

**Comment by dismorfo** [comment]
@mauromsl Please take a look.
