### ISSUE TITLE
Missing user data: Biography, research interests and social links

### ISSUE THREAD

**Issue by mauromsl** [NYULibraries/intransition#3]
When including a user in the various object schemas, please include fields for `"biography"`, `research_interests` and `social_links` (at the moment only one `"url"` is provided for the user personal website

e.g:
https://mediacommons.org/user/3360?project=intransition
![image](https://github.com/NYULibraries/intransition/assets/10760678/e1138707-7329-4931-b088-24e07a469533)

**Comment by dismorfo** [comment]
All metadata but research_interests is now available. Unfortunately, research_interests is not part of the project instance, and the network does not share that field with the projects in the network. I do not have a straightforward way to export the information.
