### ISSUE TITLE
Expose article URL/paths

### ISSUE THREAD

**Issue by mauromsl** [NYULibraries/intransition#5]
In order to handle redirection of content from articles hosted in mediacommons to the new journal on Janeway, we need to be able to correlate them

Would it be possible to include the canonical URL or path for each of the articles?

For example this article: http://mediacommons.org/intransition/2016/10/06/don-t-look-now-paradoxes-suture could expose an attribute like `"article_path": "/intransition/2016/10/06/don-t-look-now-paradoxes-suture"` 
 
And this one https://mediacommons.org/intransition/history-world-according-getty-images could be included as `"article_path": "/intransition/history-world-according-getty-images"`

**Comment by dismorfo** [comment]
@mauromsl We are in the process of migrating to new servers. I will be able to get back to you once we are done with the migration.

**Comment by dismorfo** [comment]
@mauromsl Please take a look, the path should be available now.
